export const departments = [
  "SocialHumanities",
  "IFL",
  "Engineering",
  "Science",
  "Education",
];

export const majors = {
  Engineering: [
    "Information Technology Engineering",
    "Telecommunication and Electronic Engineering",
    "Bio Engineering",
    "Automation & Supply Chain Systems Engineering",
    "Environmental Engineering",
  ],
  SocialHumanities: [
    "History",
    "Khmer Literature",
    "Media and Communication",
    "IBM",
    "Philosophy",
    "Psychology",
    "Tourism",
  ],
  IFL: ["Chinese", "English", "Japanese", "France", "Korean"],
  Science: [
    "Physics",
    "Computer Science",
    "Chemistry",
    "Biology",
    "Mathematics",
  ],
  Education: [
    "Educational Studies",
    "Higher Education Development and Management",
    "Lifelong Learning",
    "Center for Educational Research and Training",
  ],
};

export const provinces = [
  "Phnom Penh",
  "Banteay Meanchey",
  "Battambang",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kampot",
  "Kandal",
  "Kep",
  "Koh Kong",
  "Kratie",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Preah Sihanouk",
  "Preah Vihear",
  "Pursat",
  "Ratanakiri",
  "Siem Reap",
  "Stung Treng",
  "Svay Rieng",
  "Takeo",
  "Tboung Khmum",
];

export const classes = [
  "M1",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "E1",
  "E2",
  "E3",
  "E4",
  "SH1",
  "SH2",
  "SH3",
  "SH4",
  "L1",
  "L2",
  "L3",
  "L4",
  "S1",
  "S2",
  "S3",
  "S4",
];
